# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3840a27700eb9f2cd5ec224c6bcc8af998c461e61587fec29b3d46ab12fe3e1bc56307c3cbf0374329f705eaf4ddf9eaf35d5e788eeb02fb760719e3fda09b45

test:
  secret_key_base: 72fbe20f21480b231c8e1c613e8ced24d83911e01d6ef811d078ea19fb5d246b828552c07186fc24f25db9029b618eb0b28b151a4a15e713afcd3874fbed7c63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 72fbe20f21480b231c8e1c613e8ced24d83911e01d6ef811d078ea19fb5d246b828552c07186fc24f25db9029b618eb0b28b151a4a15e713afcd3874fbed7c63# This should be secret <%= ENV["SECRET_KEY_BASE"] %>
